# Generated by Django 5.2.14 on 2026-05-21 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=10)),
                ('source', models.CharField(default='ops', max_length=32)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'agent_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_embedding', models.BinaryField()),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('agent_type', models.CharField(max_length=32)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_semantic_cache',
                'indexes': [models.Index(fields=['agent_type'], name='agent_seman_agent_t_8d7095_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_conversations',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'agent_type', 'session_id'], name='agent_conve_user_id_d2698f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('agent_type', models.CharField(db_index=True, max_length=32)),
                ('request_summary', models.TextField(default='')),
                ('response_summary', models.TextField(default='')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('prompt_version', models.CharField(default='', max_length=32)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_type', 'created_at'], name='agent_logs_agent_t_24ac7a_idx'), models.Index(fields=['status', 'created_at'], name='agent_logs_status_2d08b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('source_agent', models.CharField(max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_user_preferences',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
