# Generated by Django 5.2.14 on 2026-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_phase_a_eval'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('signal_type', models.CharField(db_index=True, max_length=16)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(default='', max_length=128)),
                ('value', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ai_standardized_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'signal_type'], name='ai_standard_user_id_1fee17_idx'), models.Index(fields=['session_id', 'created_at'], name='ai_standard_session_ecb1c0_idx')],
            },
        ),
    ]
