# Generated by Django 5.2.14 on 2026-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_standardizedsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingTuningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('intent', models.CharField(max_length=32)),
                ('fast_confidence', models.FloatField(default=0.0)),
                ('routing_method', models.CharField(max_length=8)),
                ('threshold_used', models.FloatField(default=0.85)),
                ('outcome', models.CharField(default='', max_length=16)),
                ('reward_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ai_routing_tuning_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['routing_method', 'outcome'], name='ai_routing__routing_8139f0_idx'), models.Index(fields=['created_at'], name='ai_routing__created_80b807_idx')],
            },
        ),
    ]
