# Generated by Django 5.2.14 on 2026-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_routingtuninglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('query', models.TextField()),
                ('intent', models.CharField(default='', max_length=32)),
                ('routing_conf', models.FloatField(default=0.0)),
                ('ui_state', models.CharField(default='', max_length=32)),
                ('reply', models.TextField(default='')),
                ('phases', models.JSONField(default=list)),
                ('ranked_before', models.JSONField(default=list)),
                ('ranked_after', models.JSONField(default=list)),
                ('signals_applied', models.JSONField(default=dict)),
                ('block_count', models.IntegerField(default=0)),
                ('total_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ai_session_traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='ai_session__user_id_d6a0ca_idx'), models.Index(fields=['intent'], name='ai_session__intent_8ef99e_idx')],
            },
        ),
    ]
