# Generated by Django 5.2.14 on 2026-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_sessiontrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontrace',
            name='events',
            field=models.JSONField(default=list),
        ),
    ]
