# Generated by Django 5.2.14 on 2026-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_sessiontrace_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontrace',
            name='decision_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
