# Generated by Django 5.2.14 on 2026-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_add_conversation_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('current_step', models.CharField(default='idle', max_length=32)),
                ('selected_order_id', models.IntegerField(blank=True, null=True)),
                ('confirm_type', models.CharField(blank=True, max_length=32, null=True)),
                ('confirm_token', models.CharField(blank=True, max_length=64, null=True)),
                ('confirm_expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('orders_snapshot', models.JSONField(blank=True, default=list)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_workflows',
                'indexes': [models.Index(fields=['session_id'], name='order_workf_session_2ec09c_idx'), models.Index(fields=['user_id', '-updated_at'], name='order_workf_user_id_f749bd_idx')],
            },
        ),
    ]
