# Generated by Django 5.2.14 on 2026-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_add_order_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
