# Generated by Django 5.2.14 on 2026-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_add_conversation_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='last_purchase',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
