# Generated by Django 5.2.14 on 2026-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_add_session_last_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('workflow_id', models.CharField(max_length=64)),
                ('current_step', models.CharField(default='idle', max_length=32)),
                ('focused_item', models.JSONField(blank=True, null=True)),
                ('focused_at', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents_cart_workflow',
                'indexes': [models.Index(fields=['session_id'], name='agents_cart_session_7df9d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('workflow_id', models.CharField(max_length=64)),
                ('current_step', models.CharField(default='idle', max_length=32)),
                ('selected_product_id', models.IntegerField(blank=True, null=True)),
                ('confirm_type', models.CharField(default='', max_length=32)),
                ('confirm_token', models.CharField(default='', max_length=64)),
                ('confirm_expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(default='', max_length=64)),
                ('snapshot_hash', models.CharField(default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents_purchase_workflow',
                'indexes': [models.Index(fields=['session_id'], name='agents_purc_session_5a232d_idx')],
            },
        ),
    ]
