# Generated by Django 5.2.14 on 2026-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_cart_purchase_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pending_intent', models.CharField(default='', max_length=32)),
                ('collected_slots', models.JSONField(default=dict)),
                ('missing_slots', models.JSONField(default=list)),
                ('last_intent', models.CharField(default='', max_length=32)),
                ('pending_action_type', models.CharField(default='', max_length=32)),
                ('pending_question', models.TextField(default='')),
                ('pending_options', models.JSONField(default=dict)),
                ('original_query', models.TextField(default='')),
                ('context_summary', models.TextField(default='')),
                ('injected_slot', models.TextField(default='')),
                ('last_user_query', models.TextField(default='')),
                ('expects_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'agent_session_state',
                'indexes': [models.Index(fields=['expires_at'], name='agent_sessi_expires_130d31_idx')],
            },
        ),
    ]
