# Generated by Django 5.2.14 on 2026-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_session_state_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstate',
            name='shared_view',
            field=models.JSONField(default=dict),
        ),
    ]
