# Generated by Django 5.2.14 on 2026-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_phase6_shared_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstate',
            name='pending_reference',
            field=models.JSONField(default=None, null=True),
        ),
    ]
