# Generated by Django 5.2.14 on 2026-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID（purchase_id）'),
        ),
        migrations.AddField(
            model_name='refund',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID（refund_id）'),
        ),
    ]
