# Generated by Django 4.2.30 on 2026-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_deleted',
            field=models.BooleanField(default=False, verbose_name='买家已删除'),
        ),
    ]
