# Generated by Django 5.2.14 on 2026-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='Refund reason'),
        ),
    ]
