# Generated by Django 5.2.14 on 2026-05-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_legacy_id_refund_legacy_id'),
        ('orders', '0007_order_idx_order_status_order_idx_order_created_and_more'),
    ]

    operations = [
    ]
