# Generated by Django 5.2.14 on 2026-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260523_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='legacy_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('refunding', 'Refunding'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='paid', max_length=20, verbose_name='订单状态'),
        ),
    ]
