# Generated by Django 5.2.14 on 2026-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID（product_id）'),
        ),
        migrations.AddField(
            model_name='review',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID（review_id）'),
        ),
        migrations.AddField(
            model_name='shop',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='旧系统ID（store_id）'),
        ),
    ]
