# Generated by Django 5.2.14 on 2026-05-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('visible', '可见'), ('hidden', '隐藏'), ('deleted', '已删除'), ('reported', '被举报')], default='visible', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('disabled', '已禁用')], default='approved', max_length=20, verbose_name='店铺状态'),
        ),
    ]
