# Generated by Django 5.2.14 on 2026-05-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_active_review_status_shop_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
