# Generated by Django 5.2.14 on 2026-05-11 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_idx_order_status_order_idx_order_created_and_more'),
        ('products', '0009_product_fulltext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['change_type', 'created_at'], name='idx_inv_txn_type_time'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_product_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='idx_product_cat_active'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='idx_review_status'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='idx_review_created'),
        ),
    ]
