# Generated by Django 5.2.14 on 2026-05-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_legacy_id_product_legacy_id_and_more'),
        ('products', '0011_remove_inventory_reserved_quantity_and_more'),
    ]

    operations = [
    ]
