# Generated by Django 5.2.14 on 2026-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20260523_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='legacy_id',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='available', max_length=20, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('visible', '可见'), ('hidden', '隐藏'), ('deleted', '已删除'), ('reported', '被举报')], default='hidden', max_length=20, verbose_name='审核状态'),
        ),
    ]
