# Generated by Django 5.2.14 on 2026-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='续航(小时)'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='蓝牙版本'),
        ),
        migrations.AddField(
            model_name='product',
            name='noise_cancellation',
            field=models.BooleanField(default=False, verbose_name='主动降噪'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展规格'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='重量(g)'),
        ),
    ]
