# Generated by Django 5.2.14 on 2026-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='评分 1.0-5.0'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='热度排名(越小越热)'),
        ),
    ]
