# Generated by Django 4.2.30 on 2026-05-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20, verbose_name='操作类型')),
                ('table_name', models.CharField(max_length=50, verbose_name='操作表')),
                ('record_id', models.CharField(max_length=50, verbose_name='记录ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
