# Generated by Django 5.2.14 on 2026-05-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_auditlog_idx_audit_action_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='变更表')),
                ('record_id', models.CharField(max_length=50, verbose_name='记录ID')),
                ('action', models.CharField(max_length=30, verbose_name='操作类型')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='变更前JSON')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='变更后JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '变更日志',
                'verbose_name_plural': '变更日志',
                'db_table': 'change_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_name', 'created_at'], name='idx_clog_table_time'), models.Index(fields=['created_at'], name='idx_clog_time')],
            },
        ),
    ]
