"""Django models for AI Agent persistence.

All agent data lives in MySQL alongside the ShopEase application data.
"""

from django.db import models
from django.conf import settings


# ── AgentLog — every LLM call recorded ──────────────────────────

class AgentLog(models.Model):
    """Immutable audit trail of every agent invocation."""

    trace_id = models.CharField(max_length=64, unique=True, db_index=True)
    agent_type = models.CharField(max_length=32, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='agent_logs')
    request_summary = models.TextField(default='')
    response_summary = models.TextField(default='')
    tokens_used = models.PositiveIntegerField(default=0)
    prompt_version = models.CharField(max_length=32, default='')
    latency_ms = models.PositiveIntegerField(default=0)
    cache_hit = models.BooleanField(default=False)
    status = models.CharField(max_length=16, default='ok')  # ok|degraded|failed
    error = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'agent_logs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['agent_type', 'created_at']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f"[{self.agent_type}] {self.status} ({self.tokens_used}tok)"


# ── AgentConversation — multi-turn dialogue history ─────────────

class AgentConversation(models.Model):
    """Per-user, per-agent conversation history."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='agent_conversations',
        null=True, blank=True)                         # null → guest users
    agent_type = models.CharField(max_length=32)   # customer_service | recommend
    session_id = models.CharField(max_length=64, db_index=True)
    role = models.CharField(max_length=16)          # user | assistant | tool
    content = models.TextField()
    metadata = models.JSONField(default=dict, blank=True)  # blocks, artifacts
    tokens_used = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'agent_conversations'
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['user', 'agent_type', 'session_id']),
        ]


# ── UserPreference — extracted user preferences ─────────────────

class UserPreference(models.Model):
    """Preferences extracted by agents from user conversations."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='agent_preferences')
    key = models.CharField(max_length=64)           # e.g. "preferred_color"
    value = models.TextField()                      # e.g. "red"
    source_agent = models.CharField(max_length=32)  # which agent extracted this
    confidence = models.FloatField(default=1.0)     # 0.0 – 1.0
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'agent_user_preferences'
        unique_together = [('user', 'key')]


# ── SemanticCache — question → answer cache ─────────────────────

class SemanticCache(models.Model):
    """Cached LLM responses keyed by question embedding."""

    query_embedding = models.BinaryField()          # numpy → bytes
    query_text = models.TextField()
    response_text = models.TextField()
    agent_type = models.CharField(max_length=32)
    hit_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'agent_semantic_cache'
        indexes = [
            models.Index(fields=['agent_type']),
        ]


# ── AgentAlert — ops monitoring alerts ──────────────────────────

class AgentAlert(models.Model):
    """Alerts generated by the OpsAgent."""

    class Severity(models.TextChoices):
        CRITICAL = 'critical', 'Critical'
        WARNING = 'warning', 'Warning'
        INFO = 'info', 'Info'

    title = models.CharField(max_length=200)
    description = models.TextField()
    severity = models.CharField(
        max_length=10, choices=Severity.choices, default=Severity.INFO)
    source = models.CharField(max_length=32, default='ops')
    resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'agent_alerts'
        ordering = ['-created_at']


# ── EvaluationEvent — user behaviour tracking ────────────────────

class EvaluationEvent(models.Model):
    """Per-interaction event for offline+online evaluation loop.

    Tracks: impressions, clicks, purchases, dismisses, clarify answers.
    outcome_type + success enable CTR/CVR/success-rate metrics.
    """
    session_id   = models.CharField(max_length=64, db_index=True)
    query_type   = models.CharField(max_length=32, db_index=True)  # recommend/search/chat/clarify
    event_type   = models.CharField(max_length=32)  # impression/click/dismiss/skip/clarify/clarify_ask/clarify_answer/fallback
    product_id   = models.IntegerField(null=True, blank=True)
    duration_ms  = models.IntegerField(null=True, blank=True)
    outcome_type = models.CharField(max_length=32, default='')  # clicked/purchased/ignored/abandoned/refined_query/clarified
    success      = models.BooleanField(default=False)
    metadata     = models.JSONField(default=dict, blank=True)
    created_at   = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'ai_evaluation_events'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['query_type', 'created_at']),
            models.Index(fields=['event_type', 'success']),
            models.Index(fields=['outcome_type']),
            models.Index(fields=['session_id', 'created_at']),
        ]

    def __str__(self):
        return f"[{self.event_type}] {self.query_type} success={self.success}"


# ── StandardizedSignal — Phase B signal normalization ────────

class StandardizedSignal(models.Model):
    """Standardized user behavior signal with semantic classification.

    Raw events (clicks, purchases, clarify answers) are classified into
    SignalType by the SignalClassifier, then stored here for downstream
    consumption by ranking feedback, memory distribution, and routing tuning.
    """
    session_id  = models.CharField(max_length=64, db_index=True)
    user_id     = models.IntegerField(null=True, blank=True)
    signal_type = models.CharField(max_length=16, db_index=True)  # exploration/intent/conversion/negative/stated
    product_id  = models.IntegerField(null=True, blank=True)
    category    = models.CharField(max_length=128, default='')
    value       = models.FloatField(default=0.0)  # signal weight
    metadata    = models.JSONField(default=dict, blank=True)
    created_at  = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'ai_standardized_signals'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user_id', 'signal_type']),
            models.Index(fields=['session_id', 'created_at']),
        ]

    def __str__(self):
        return f"[{self.signal_type}] user={self.user_id} product={self.product_id}"


# ── RoutingTuningLog — Phase B-3 routing accuracy tracking ──

class RoutingTuningLog(models.Model):
    """Records each routing decision and its eventual outcome for online tuning."""
    session_id       = models.CharField(max_length=64, db_index=True)
    intent           = models.CharField(max_length=32)        # the routed intent
    fast_confidence  = models.FloatField(default=0.0)         # fast classifier confidence
    routing_method   = models.CharField(max_length=8)         # 'fast' or 'slow'
    threshold_used   = models.FloatField(default=0.85)        # threshold at decision time
    outcome          = models.CharField(max_length=16, default='')  # clicked/purchased/dismissed/requeried/unknown
    reward_score     = models.FloatField(default=0.0)         # -1 to 1
    created_at       = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'ai_routing_tuning_log'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['routing_method', 'outcome']),
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f"[{self.routing_method}] {self.intent} → {self.outcome} (reward={self.reward_score:.2f})"


# ── ConversationSession — UI chat session metadata ────────────

class ConversationSession(models.Model):
    """Chat session container for the AI Workspace sidebar.

    Maps 1:N to AgentConversation messages.
    NOT the same as AgentState.session_id (runtime graph state).
    """
    session_id      = models.CharField(max_length=64, unique=True, db_index=True)
    user            = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='chat_sessions',
        null=True, blank=True)                       # null → guest
    title           = models.CharField(max_length=200, default='', blank=True)
    last_message_at = models.DateTimeField(auto_now=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    last_purchase   = models.JSONField(default=dict, blank=True)  # {order_id, order_no, product_name, price, created_at}

    class Meta:
        db_table = 'conversation_sessions'
        ordering = ['-last_message_at']
        indexes = [
            models.Index(fields=['user', '-last_message_at']),
        ]

    def __str__(self):
        return f"[{self.session_id[:8]}] {self.title[:40]}"


# ── OrderWorkflow — OrderAgent transaction state ────────────

class OrderWorkflow(models.Model):
    """Persistent workflow state for OrderAgent multi-turn transactions.

    Separate from CommerceAgent's pending_slots — this is transactional
    state (selected_order, confirmation), not constraint clarification.
    """
    workflow_id     = models.CharField(max_length=64, unique=True, db_index=True)
    session_id      = models.CharField(max_length=64, db_index=True)
    user_id         = models.IntegerField(null=True, blank=True)
    current_step    = models.CharField(max_length=32, default="idle")  # OrderStep
    selected_order_id = models.IntegerField(null=True, blank=True)
    confirm_type    = models.CharField(max_length=32, null=True, blank=True)
    confirm_token   = models.CharField(max_length=64, null=True, blank=True)
    confirm_expires_at = models.DateTimeField(null=True, blank=True)
    idempotency_key = models.CharField(max_length=64, null=True, blank=True)
    orders_snapshot = models.JSONField(default=list, blank=True)
    snapshot_at     = models.DateTimeField(null=True, blank=True)
    snapshot_hash   = models.CharField(max_length=32, null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'order_workflows'
        indexes = [
            models.Index(fields=['session_id']),
            models.Index(fields=['user_id', '-updated_at']),
        ]

    def __str__(self):
        return f"[{self.workflow_id[:8]}] step={self.current_step}"


# ── SessionTrace — Phase B-4 replay + diff infrastructure ──

class SessionTrace(models.Model):
    """Full AI session trace for replay, diff, and observability."""
    session_id      = models.CharField(max_length=64, unique=True, db_index=True)
    user_id         = models.IntegerField(null=True, blank=True)
    query           = models.TextField()
    intent          = models.CharField(max_length=32, default='')
    routing_conf    = models.FloatField(default=0.0)
    ui_state        = models.CharField(max_length=32, default='')
    reply           = models.TextField(default='')
    phases          = models.JSONField(default=list)        # [{phase, label, ms}, ...]
    events          = models.JSONField(default=list)        # [{block, type, ms, payload}, ...]
    ranked_before   = models.JSONField(default=list)        # [{id, name, price, category}, ...]
    ranked_after    = models.JSONField(default=list)        # [{id, name, price, category}, ...]
    signals_applied = models.JSONField(default=dict)        # {category: boost, ...}
    block_count     = models.IntegerField(default=0)
    total_ms        = models.IntegerField(default=0)
    decision_trace  = models.JSONField(default=dict, blank=True)  # P0: DecisionTrace schema
    created_at      = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'ai_session_traces'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user_id', 'created_at']),
            models.Index(fields=['intent']),
        ]

    def __str__(self):
        return f"[{self.intent}] {self.query[:50]} ({self.total_ms}ms)"
