"""Django models for AI Agent persistence.

All agent data lives in MySQL alongside the ShopEase application data.
"""

from django.db import models
from django.conf import settings


# ── AgentLog — every LLM call recorded ──────────────────────────

class AgentLog(models.Model):
    """Immutable audit trail of every agent invocation."""

    trace_id = models.CharField(max_length=64, unique=True, db_index=True)
    agent_type = models.CharField(max_length=32, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='agent_logs')
    request_summary = models.TextField(default='')
    response_summary = models.TextField(default='')
    tokens_used = models.PositiveIntegerField(default=0)
    prompt_version = models.CharField(max_length=32, default='')
    latency_ms = models.PositiveIntegerField(default=0)
    cache_hit = models.BooleanField(default=False)
    status = models.CharField(max_length=16, default='ok')  # ok|degraded|failed
    error = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'agent_logs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['agent_type', 'created_at']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f"[{self.agent_type}] {self.status} ({self.tokens_used}tok)"


# ── AgentConversation — multi-turn dialogue history ─────────────

class AgentConversation(models.Model):
    """Per-user, per-agent conversation history."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='agent_conversations')
    agent_type = models.CharField(max_length=32)   # customer_service | recommend
    session_id = models.CharField(max_length=64, db_index=True)
    role = models.CharField(max_length=16)          # user | assistant | tool
    content = models.TextField()
    tokens_used = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'agent_conversations'
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['user', 'agent_type', 'session_id']),
        ]


# ── UserPreference — extracted user preferences ─────────────────

class UserPreference(models.Model):
    """Preferences extracted by agents from user conversations."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='agent_preferences')
    key = models.CharField(max_length=64)           # e.g. "preferred_color"
    value = models.TextField()                      # e.g. "red"
    source_agent = models.CharField(max_length=32)  # which agent extracted this
    confidence = models.FloatField(default=1.0)     # 0.0 – 1.0
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'agent_user_preferences'
        unique_together = [('user', 'key')]


# ── SemanticCache — question → answer cache ─────────────────────

class SemanticCache(models.Model):
    """Cached LLM responses keyed by question embedding."""

    query_embedding = models.BinaryField()          # numpy → bytes
    query_text = models.TextField()
    response_text = models.TextField()
    agent_type = models.CharField(max_length=32)
    hit_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'agent_semantic_cache'
        indexes = [
            models.Index(fields=['agent_type']),
        ]


# ── AgentAlert — ops monitoring alerts ──────────────────────────

class AgentAlert(models.Model):
    """Alerts generated by the OpsAgent."""

    class Severity(models.TextChoices):
        CRITICAL = 'critical', 'Critical'
        WARNING = 'warning', 'Warning'
        INFO = 'info', 'Info'

    title = models.CharField(max_length=200)
    description = models.TextField()
    severity = models.CharField(
        max_length=10, choices=Severity.choices, default=Severity.INFO)
    source = models.CharField(max_length=32, default='ops')
    resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'agent_alerts'
        ordering = ['-created_at']
