# Generated by Django 5.2.14 on 2026-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='测试数据导入时的原始ID映射', null=True, unique=True, verbose_name='旧系统ID'),
        ),
    ]
